### ISSUE TITLE
How to save my character's every frame pose?

### ISSUE THREAD

**Issue by iamannamiao** [Elem8100/MapleNecrocer#13]
Dear author, I have download the newest version of Maple Necrocer. I want to save my character's every frame pose, and there was a function named "Save" next to "Spawn" before, but I can't find it now.
But now it can only be stored in Stand mode? Thanks for your reply.

作者您好~ 先前紙娃娃能夠依每個影格姿勢&調整範圍並儲存，現在那個功能似乎不見了?
請問是改到別的地方了還是以後只能儲存stand姿勢呢? 謝謝回覆

**Comment by Elem8100** [comment]
這功能已經加入了
