### ISSUE TITLE
怪物沒有圖片

### ISSUE THREAD

**Issue by zo6-zo6** [Elem8100/MapleNecrocer#14]
TMS257版本

Mob_001.wz
_Canvas_050.wz

9601974/深淵妖怪綿羊
9601975/深淵暗黑妖怪綿羊
9601976/深淵大師哈維
9601977/深淵暗黑大師哈維
9601978/深淵妖怪侏儒
9601979/深淵噴火龍

**Comment by Elem8100** [comment]
那些怪物的圖片都是透明的,不會顯示出來
並不是bug

**Comment by zo6-zo6** [comment]
我找到了 是在AbyssExpeditionMob_000.wz 這裡面
