### ISSUE TITLE
The 'Portal Info' is not running

### ISSUE THREAD

**Issue by lumyjuwon** [Elem8100/MapleNecrocer#21]
![image](https://github.com/Elem8100/MapleNecrocer/assets/32597561/56581a46-5f6c-4f68-80af-d3e8d97867bc)

I clicked on 'Portal Info' in the View menu, but the portal information did not appear.

If this bug is solved then can i see the portal name ("pn")?

Thanks.

**Comment by Elem8100** [comment]
Fixed !

**Comment by lumyjuwon** [comment]
@Elem8100 It works very well! Thank you!
