### ISSUE TITLE
Please let us see skills Hitbox sizes.

### ISSUE THREAD

**Issue by Linkinbr** [Elem8100/MapleNecrocer#22]
On the "Skill" tab please let us see the hitbox size (in pixels?) of the skills when hovering.
Thank you so much, this program is great.

**Comment by Elem8100** [comment]
What do you mean about "hitbox" ?

**Comment by Elem8100** [comment]
![skill_1121210560](https://github.com/Elem8100/MapleNecrocer/assets/49195287/b71215b5-4b58-4497-83b8-d5a4a6b2a033)

lt and rb's  attankk  range ?

**Comment by Elem8100** [comment]
Added
