### ISSUE TITLE
dotnet run后报错 Could not f ind a part of the path '\\Mac\Home\Desktop\MapleNecrocer\MapleNecrocer\Resources\01050088.img.info.iconRaw.png'

### ISSUE THREAD

**Issue by 740099814** [Elem8100/MapleNecrocer#23]
Could not f
ind a part of the path '\\Mac\Home\Desktop\MapleNecrocer\MapleNecrocer\Resources\01050088.img.info.iconRaw.png'

**Comment by 740099814** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2299.7">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Helvetica}
table.t1 {border-style: solid; border-width: 0.5px 0.5px 0.5px 0.5px; border-color: #bfbfbf #bfbfbf #bfbfbf #bfbfbf; border-collapse: collapse}
td.td1 {border-style: solid; border-width: 0.5px 0.5px 0.5px 0.5px; border-color: #7f7f7f #7f7f7f #7f7f7f #7f7f7f; padding: 0.0px 5.0px 0.0px 5.0px}
</style>
</head>
<body>

严重性 | 代码 | 说明 | 项目 | 文件 | 行 | 禁止显示状态
-- | -- | -- | -- | -- | -- | --
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.HasNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.HasNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 244 | 活动
错误 | CS1061 | “Skill”未包含“VehicleID”的定义，并且找不到可接受第一个“Skill”类型参数的可访问扩展方法“VehicleID”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\SkillTooltipRender2.cs | 50 | 活动
错误 | CS1061 | “Skill”未包含“NotIncBuffDuration”的定义，并且找不到可接受第一个“Skill”类型参数的可访问扩展方法“NotIncBuffDuration”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\SkillTooltipRender2.cs | 338 | 活动
错误 | CS1061 | “Skill”未包含“NotCooltimeReset”的定义，并且找不到可接受第一个“Skill”类型参数的可访问扩展方法“NotCooltimeReset”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\SkillTooltipRender2.cs | 342 | 活动
错误 | CS1503 | 参数 1: 无法从“WzComparerR2.WzLib.Wz_Node”转换为“WzComparerR2.WzLib.Wz_File” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\MainForm.cs | 558 | 活动
错误 | CS1503 | 参数 2: 无法从“WzComparerR2.WzLib.Wz_Node”转换为“WzComparerR2.WzLib.Wz_File” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\MainForm.cs | 558 | 活动
错误 | CS1503 | 参数 3: 无法从“WzComparerR2.WzLib.Wz_Node”转换为“WzComparerR2.WzLib.Wz_File” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\MainForm.cs | 558 | 活动
错误 | CS0117 | “Resources”未包含“resize_picture_icon”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\MainForm.Designer.cs | 616 | 活动
错误 | CS0117 | “Resources”未包含“Aha_Soft_Hardware_Floppy_32”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\MainForm.Designer.cs | 705 | 活动
错误 | CS0117 | “GearPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\AfrmItem.cs | 540 | 活动
错误 | CS0117 | “ItemPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\AfrmItem.cs | 584 | 活动
错误 | CS0117 | “GearPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 248 | 活动
错误 | CS0117 | “GearPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 372 | 活动
错误 | CS0117 | “GearPropType”未包含“Etuc”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 839 | 活动
错误 | CS0117 | “GearPropType”未包含“plusToSetItem”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 857 | 活动
错误 | CS0117 | “GearPropType”未包含“noLookChange”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 1366 | 活动
错误 | CS0117 | “GearPropType”未包含“noLookChange”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\GearTooltipRender2.cs | 1368 | 活动
错误 | CS0117 | “ItemPropType”未包含“tamingMob”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 188 | 活动
错误 | CS0117 | “ItemPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 414 | 活动
错误 | CS0117 | “ItemPropType”未包含“BLACKPINKLabel”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 555 | 活动
错误 | CS0117 | “ItemPropType”未包含“consumeCure”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 675 | 活动
错误 | CS0117 | “ItemPropType”未包含“exchangeableOnce”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 1021 | 活动
错误 | CS0117 | “ItemPropType”未包含“exchangeableOnce”的定义 | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\ItemTooltipRender2.cs | 1023 | 活动
错误 | CS1061 | “Mob”未包含“PartyBonusMob”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“PartyBonusMob”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 55 | 活动
错误 | CS1061 | “Mob”未包含“PartyBonusMob”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“PartyBonusMob”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 59 | 活动
错误 | CS1061 | “Mob”未包含“ChangeableMob”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“ChangeableMob”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 79 | 活动
错误 | CS1061 | “Mob”未包含“AllyMob”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“AllyMob”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 83 | 活动
错误 | CS1061 | “Mob”未包含“FixedBodyAttackDamageR”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“FixedBodyAttackDamageR”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 99 | 活动
错误 | CS1061 | “Mob”未包含“FixedBodyAttackDamageR”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“FixedBodyAttackDamageR”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 101 | 活动
错误 | CS1061 | “Mob”未包含“IgnoreDamage”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“IgnoreDamage”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 103 | 活动
错误 | CS1061 | “Mob”未包含“IgnoreMoveImpact”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“IgnoreMoveImpact”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 107 | 活动
错误 | CS1061 | “Mob”未包含“IgnoreMovable”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“IgnoreMovable”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 111 | 活动
错误 | CS1061 | “Mob”未包含“NoDebuff”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“NoDebuff”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 115 | 活动
错误 | CS1061 | “Mob”未包含“OnlyNormalAttack”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“OnlyNormalAttack”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 119 | 活动
错误 | CS1061 | “Mob”未包含“OnlyHittedByCommonAttack”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“OnlyHittedByCommonAttack”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 123 | 活动
错误 | CS1061 | “Mob”未包含“CharismaEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CharismaEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 165 | 活动
错误 | CS1061 | “Mob”未包含“CharismaEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CharismaEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 167 | 活动
错误 | CS1061 | “Mob”未包含“SenseEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“SenseEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 169 | 活动
错误 | CS1061 | “Mob”未包含“SenseEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“SenseEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 171 | 活动
错误 | CS1061 | “Mob”未包含“InsightEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“InsightEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 173 | 活动
错误 | CS1061 | “Mob”未包含“InsightEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“InsightEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 175 | 活动
错误 | CS1061 | “Mob”未包含“WillEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“WillEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 177 | 活动
错误 | CS1061 | “Mob”未包含“WillEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“WillEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 179 | 活动
错误 | CS1061 | “Mob”未包含“CraftEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CraftEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 181 | 活动
错误 | CS1061 | “Mob”未包含“CraftEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CraftEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 183 | 活动
错误 | CS1061 | “Mob”未包含“CharmEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CharmEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 185 | 活动
错误 | CS1061 | “Mob”未包含“CharmEXP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“CharmEXP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 187 | 活动
错误 | CS1061 | “Mob”未包含“WP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“WP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 189 | 活动
错误 | CS1061 | “Mob”未包含“WP”的定义，并且找不到可接受第一个“Mob”类型参数的可访问扩展方法“WP”(是否缺少 using 指令或程序集引用?) | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\CharaSimControl\MobTooltipRenderer.cs | 191 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.HasNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.HasNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 30 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 35 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 46 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 61 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 62 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 67 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 68 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 70 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 71 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 72 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 73 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.HasNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.HasNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 133 | 活动
错误 | CS0121 | 以下方法或属性之间的调用具有二义性:“WzComparerR2.Common.Wz_NodeExtension2.GetNode(WzComparerR2.WzLib.Wz_Node, string)”和“MapleNecrocer.Wz_NodeExtension3.GetNode(WzComparerR2.WzLib.Wz_Node, string)” | MapleNecrocer | E:\MapleNecrocer\MapleNecrocer\Client\UI\MiniMap.cs | 138 | 活动


</body>
</html>

**Comment by Elem8100** [comment]
This tool only work with Windows 10/11

**Comment by jychen105** [comment]
I also got same compile error on Windows 11, vs2022。

**Comment by Kurodake** [comment]
@Elem8100 
目前專案缺少下列條件，所以沒辦法Clone後直接編譯，不確定是不是您故意留著這些問題呢@@

MainForm.Designer.cs 裡面有三個物件的Image沒有包含在MainForm.resx資源檔案裡面
第616行 ScaleButton.Image = Properties.Resources.resize_picture_icon;
第690行 AvatarButton.Image = Properties.Resources._01050088_img_info_iconRaw;
第705行 SaveMapButton.Image = Properties.Resources.Aha_Soft_Hardware_Floppy_32;
上述三行看起來是引用了Properties/Resources.resx資源檔，但是打開該資源檔案裡面只有
<data name="01050088.img.info.iconRaw" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\Resources\01050088.img.info.iconRaw.png;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
</data>
而且還是直接抓\Resources\目錄底下的檔案 01050088.img.info.iconRaw.png，但是專案的該目錄底下沒包含該檔案

另外專案的WzComparerR2.Common缺失不少宣告，導致MapleNecrocer編譯會說缺少"某某某"的定義
@740099814 就像他上面貼出來的一樣

**Comment by Elem8100** [comment]
直接從我的硬碟copy出來，一定可以編譯
https://www.mediafire.com/file/2ave687i2dr1ggp/MapleNecrocer.zip/file

**Comment by genhao820320** [comment]
Hello, I would like to ask you, I use the latest source code to build the file, and many errors occur. What is missing? If I use the version you provided above, it can be built, but the latest one cannot be built successfully.

**Comment by 740099814** [comment]
已经解决
