### ISSUE TITLE
阿爾卡娜，利曼等地圖背景無法完全關閉

### ISSUE THREAD

**Issue by jychen105** [Elem8100/MapleNecrocer#24]
![bg_not_clear](https://github.com/Elem8100/MapleNecrocer/assets/10372311/5255accf-cfa7-435e-bcc9-7028d0c8fc7e)
如圖，請問這些動效如何關閉

**Comment by Kurodake** [comment]
作者沒設計開關選項 ， 你可以在 MapleNecrocer\Client\MapleMap.cs 底下找到 LoadMap 這個函數 然後註解掉Particle.Create();這一行

**Comment by jychen105** [comment]
git拉下來的代碼暫時未編譯通過。不過通過修改wz,刪除particle節點可以關閉粒子效果顯示。
