### ISSUE TITLE
The teleport does not show.

### ISSUE THREAD

**Issue by lumyjuwon** [Elem8100/MapleNecrocer#33]
![화면 캡처 2024-07-11 144450](https://github.com/Elem8100/MapleNecrocer/assets/32597561/85f612d2-b3e9-4085-a143-b86487c1ce5f)

I want to see teleport with [portal info](https://github.com/Elem8100/MapleNecrocer/issues/21) but just only portal show in MapleNecrocer.

Could you add a feature about teleport like posted screenshot?

Thanks.

**Comment by Elem8100** [comment]
Added
