### ISSUE TITLE
Stop monster movement

### ISSUE THREAD

**Issue by lumyjuwon** [Elem8100/MapleNecrocer#34]
Is there a function that stop monster movement? If the function is added then see more easily position of monster.  

and could you write docs of compiling MapleNecrocer? then I can contribute even a little bit.

**Comment by Elem8100** [comment]
in Client/Mob.cs, add this line of code(return;)

public override void DoMove(float Delta)
{  
       **return;**
       base.DoMove(Delta);
      ..................
      ..................
