### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by not-ebx** [Elem8100/MapleNecrocer#41]
I'm trying to build the latest version but no luck. I want to send a PR adding support for Data.wz clients, so you cna open up old clients, but no luck building. I saw you uploaded a september version on another issue and that built normally, but newest one can't.

Can you help me out?

**Comment by Elem8100** [comment]
Why PR? This supported Data.wz for a long time.

https://www.mediafire.com/file/t0t7bpjrpvc05fh/[MapleNecrocer](https://www.mediafire.com/file/t0t7bpjrpvc05fh/MapleNecrocer.zip/file).zip/file

**Comment by not-ebx** [comment]
I'll check that out!
About the Data.wz support, you are right! But for older versions it doesn't seem to work, so I wanna take a look.
Versions KMS 1.21 ~ 1.36. Beta/Alpha versions with the oldest UI.
If you are interested, this is the installer for the KMS 1.21: https://mega.nz/file/9p1xWKRT#V8TodI8Y2cBNnH2yQs9fQOPUkIFyD2kjdi5tU25lflE

**Comment by not-ebx** [comment]
The building now works! Thank you so much 😄 
I'm now working on a fix for those REALLY old versions, turns out those versions only contain the string inside `info` folder, for Mob, Map, Character, Item, etc.

**Comment by Elem8100** [comment]
work.
Thanks for the PR and contribution.
