### ISSUE TITLE
提示框內文字過小，框框顯示異常

### ISSUE THREAD

**Issue by zo6-zo6** [Elem8100/MapleNecrocer#5]
![1698160181869](https://github.com/Elem8100/MapleNecrocer/assets/142676416/cec6c0e1-4026-4453-8517-ba024942efb2)

**Comment by Elem8100** [comment]
請勿變更DPI設定，我這是固定的

**Comment by zo6-zo6** [comment]
確認過設定都是100%
是否還有其他地方影響? 

![1](https://github.com/Elem8100/MapleNecrocer/assets/142676416/70c7373d-91df-45d8-9106-e9c95dc84de1)
![2](https://github.com/Elem8100/MapleNecrocer/assets/142676416/dc69b627-82d3-4d25-9251-5ea6f092d92f)

**Comment by Elem8100** [comment]
可能與Windows11不相容吧 ，我用Windows10是正常的
另外試試DPI看可不可以:   點擊MapleNecrocer.exe->  滑鼠右鍵->內容->相容性

![Image 1](https://github.com/Elem8100/MapleNecrocer/assets/49195287/8c7bd210-ab40-40e8-93d1-4df8ea00a8a3)

**Comment by zo6-zo6** [comment]
我目前已經有設定
可是還會顯示異常
我兩台電腦測試下來都是這樣

![1698256976873](https://github.com/Elem8100/MapleNecrocer/assets/142676416/38604fee-40c2-4d75-96b7-55586967313d)

**Comment by Elem8100** [comment]
找到問題了， 已修復

**Comment by zo6-zo6** [comment]
框框顯示問題修正了
但是他會突然消失

![1698319026141](https://github.com/Elem8100/MapleNecrocer/assets/142676416/116854ce-7953-4ccd-b1fa-d6ec57abf75b)

**Comment by Elem8100** [comment]
Avatar也一樣嗎?

**Comment by zo6-zo6** [comment]
目前只有Medal 有機率會觸發到這個問題
其他目前測試下來沒有問題~~我在幫你觀察看看

**Comment by Elem8100** [comment]
我試了很多次都沒發生， 這問題就略過不管了， 因為也無法修
