### ISSUE TITLE
Fast animation

### ISSUE THREAD

**Issue by EY4WE** [Elem8100/MapleNecrocer#6]
I still haven't seen anyone reporting on this so I'm not sure, but all the animations are very fast
Is this intentional? Or is this a issue that only occurs in my environment?
I use it mainly with JMS and have not had any problems except for the fast animations, and it is a great client :)

https://github.com/Elem8100/MapleNecrocer/assets/137525528/b3b264ec-1fb5-4715-98f9-c853a52c5287

**Comment by Elem8100** [comment]
Fixed.
Try it again.

**Comment by Elem8100** [comment]
Your monitor refresh rate must change to 60Hz and Vsync On.

**Comment by EY4WE** [comment]
I changed from 144Hz to 60Hz and the animation speed is indeed normal. But to be honest, it is a hassle to change to 60Hz only when using this client...
Well, even if the animation speed is fast, it is not a problem for easily changing newly added avatars and doing other things, so I will use 144Hz as it is. Thank you :)
