### ISSUE TITLE
點選的項目，跟上方顯示的不一樣

### ISSUE THREAD

**Issue by zo6-zo6** [Elem8100/MapleNecrocer#7]
![1699280748453](https://github.com/Elem8100/MapleNecrocer/assets/142676416/2371dbd1-11fb-402f-8f04-f24b77465a2b)

**Comment by zo6-zo6** [comment]
如果用搜尋的才會觸發到這問題

**Comment by zo6-zo6** [comment]
打字搜尋才會觸發到這個問題

**Comment by zo6-zo6** [comment]
1106的嗎?

**Comment by Elem8100** [comment]
1106已修復了
